apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubelens.fullname" . }}-policy
  labels:
    {{- include "kubelens.labels" . | nindent 4 }}
data:
  policy.json: |
{{ .Values.policyConfig | toJson | indent 4 }}
