# DevInt – nginx, HTTP on Ingress. See README.
namespace: apps-devintkubelens

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - kubelens.d4n-devint.eu.novartis.net
  tls:
    enabled: false
    hosts:
      - kubelens.d4n-devint.eu.novartis.net
